import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <div className="flex flex-col md:flex-row min-h-screen">
          {/* First section - 2/3 width on desktop, full width on mobile */}
          <div className="w-full md:w-2/3 flex flex-col">
            {/* First subsection - 2/3 height */}
            <div className="h-2/3 md:h-2/3 bg-blue-100">
              {children}
            </div>
            {/* Second subsection - 1/3 height */}
            <div className="h-1/3 md:h-1/3 bg-green-100">
              {/* Content for second subsection */}
            </div>
          </div>
          
          {/* Second section - 1/3 width on desktop, full width on mobile */}
          <div className="w-full md:w-1/3 bg-purple-100">
            {/* Content for second section */}
          </div>
        </div>
      </body>
    </html>
  );
}
